triggers:
  - type: meya.wit
    properties:
        token: YODQDWW6XIO7HYHEDT242YKY6SKGRWIY
        intent: bookingAR
states:
    user_exist_check:
        component: meya.conditional_exists
        properties:
            scope: user
            key: phone
        transitions:
            exists: last_booking
            notexists: user_notexists_state
    last_booking:
        component: lastBookingAR
    last_booking_check:
        component: meya.conditional_exists
        properties:
            scope: flow
            key: last_booking
        transitions:
            exists: ask_if_last_booking
            notexists: single_or_package
    ask_if_last_booking:
        component: meya.text_buttons
        properties:
            text: >
                هل ترغب في أن يكون حجزك مطابقًا تمامًا للحجز السابق؟ (نفس الجدول الزمني والوقت والعنوان ..)
            buttons:
                - text: "نعم"
                  action: yes
                - text: "لا"
                  action: no
        transitions:
            yes: book_last_booking
            no: single_or_package
    book_last_booking:
        component: book_last_bookingAR
        transitions:
            transfer: transfer
    single_or_package:
        component: meya.text_buttons
        properties:
            text: >
                يرجى الاختيار بين زيارة واحدة و باقة
            buttons:
                - text: زيارة واحدة
                  action: day
                  data:
                    schedule: 0
                    booking_type: single
                - text: باقة
                  action: schedule
                  data:
                    booking_type: package
                - text: إلغاء
                  action: cancel
        transitions:
            day: day
            schedule: schedule
            cancel: end_state
    schedule:
        component: meya.text_buttons
        properties:
            text: >
                .ذيرجى تحديد عدد الزيارات في الأسبوع
            buttons:
                - text: مرة في الأسبوع
                  action: next
                  data:
                    schedule: 1
                - text: مرتين في الأسبوع
                  action: next
                  data:
                    schedule: 2
                - text: back
                  action: back
        transitions:
            back: single_or_package
            next: day
    day:
        component: meya.input_string
        properties:
            text: >
                يرجى تحديد يوم (أو أيام) في الأسبوع الذي تود أن تتم فيه الزيارة. يرجى ملاحظة أننا لا نقدم جلسات يوم الجمعة
            output: schedule
            scope: flow
    time:
        component: meya.text_buttons
        properties:
            text: >
                يرجى تحديد وقت الزيارة
            buttons:
                - text: في الصباح
                  action: next
                  data:
                    time: morning
                - text: بعد الظهر
                  action: next
                  data:
                    time: afternoon
                - text: إلغاء
                  action: cancel
        transitions:
            cancel: end_state
            next: transfer
    transfer:
        component: human.transfer
        properties:
            text: >
                لحظة واحدة بينما أقوم بوصلك مع وكيل

                قد يستغرق الأمر بضع دقائق
            note: |
                booking and custoemr's details
                address - {{ user.address }}
                booking type - {{ flow.booking_type }}
                day(s) - {{ flow.schedule }}
                time - {{ flow.time }}
            timeout: 3600
            timeout_flow: end_state2
    end_state2:
        return: true
    user_notexists_state:
        component: meya.text
        properties:
            text: >
                إذا كنت ترغب في حجز منظفة، تحتاج إلى تسجيل الدخول أو التسجيل

                عندما ترغبت في تسجيل الدخول ، فقط أخبرني
        return: true
    end_state:
        return: true