triggers:
  - type: meya.wit
    properties:
        token: 7DAEGWX5PAFWNSEJ2VZIV64R4BZKDJP7
        intent: cleanerLate
name: CleanerIsLate
states:
    First:
        component: meya.text
        properties:
            text: Thank you for your patience, we understand your concern, just to inform you that we have an open hour, for an instance if the visit is at 4 PM you might receive the cleaner starting 3 PM until 5 PM.
        delay:
            relative: 5
    Second:
        component: meya.text_buttons
        properties:
            text: Is the cleaner late more than an hour? 
            output: button_click
            buttons:
                - text: Yes
                  action: Yes
                  data:
                    foo: bar
                - text: No
                  action: No
        transitions:
            Yes: YesMoreThanAnHour
            No: NoMoreThanAnHour
        delay:
            relative: 5
    NoMoreThanAnHour:
        component: meya.text
        properties:
            text: Thank you for your quick response, I will follow up with you in a while.
            action: next
        delay:
            relative: 900
        transitions:
            next: After15Mins
    After15Mins:
        component: meya.text_buttons
        properties:
            text: I would just like to make sure, have you received the cleaner or not yet?
            output: button_click
            buttons:
                - text: Yes
                  action: YesReceived
                  data:
                    foo: bar
                - text: No
                  action: NoReceived
        transitions:
            YesReceived: YesReceived
            NoReceived: Second
        delay:
            relative: 5
    YesReceived:
        component: meya.text
        properties:
            text: "That's great, please don't hesitate to let us know if you need more help, we are here to serve you. \U0001F604"
        delay:
            relative: 5
        return: true
    YesMoreThanAnHour:
        component: human.transfer
        properties:
            text: "I will transfer you to an agent."
            note: "cleaner is more than an hour late"
            timeout: 60  # in seconds
        
        