triggers:
  - type: meya.wit
    properties:
        token: YODQDWW6XIO7HYHEDT242YKY6SKGRWIY
        intent: helpAR
states:
    help:
        component: meya.text
        properties:
            text: >
                مرحبا ، أنا أيونو بوت.
                
                فيما يلي عبارة عن بعض الكلمات أو العبارات التي قد تساعدني على خدمتكم بشكل أفضل:
                
                "تسجيل الدخول" أو "تسجيل الدخول" - لمساعدتك في تسجيل الدخول.
                
                "تسجيل" أو "تسجيل" - لإنشاء حساب.
                
                "خدمة سيئة" - للإبلاغ عن خدمة سيئة.
                
                "مساعدة" - لإظهار هذه الرسالة.
    help2:
        component: meya.text
        properties:
            text: >
                لتسجيل الدخول، على سبيل المثال، يمكنك ببساطة قول ما يلي:
                
                "أود تسجيل الدخول".