triggers:
  - type: meya.wit
    properties:
        token: 7DAEGWX5PAFWNSEJ2VZIV64R4BZKDJP7
        intent: refund
states:
    user_exist_check:
        component: meya.conditional_exists
        properties:
            scope: user
            key: phone
        transitions:
            exists: refund_check
            notexists: user_notexists_state
    refund_check:
        component: meya.text_buttons
        properties:
            text: would you like ask for a refund?
            buttons:
                - text: yes
                  action: continue
                  data:
                    refund: yes
                - text: no
                  action: end
        transitions:
            continue: transfer
            end: end_state
    transfer:
        component: human.transfer
        properties:
            text: >
                Thank you for raising this, we will escalate this to the specialized department and they will check the refund case and contact you back. Thank you for your patience.
            note: |
                Customer wants to apply for a card
                name - {{ user.first_name }} {{ user.last_name }}
                email - {{ user.email }}
                cancel - yes
    end_state2:
        return: true
    user_notexists_state:
        component: meya.text
        properties:
            text: if you wish to refund sign in
        return: true
    end_state:
        return: true