triggers:
  - type: meya.wit
    properties:
        token: 7DAEGWX5PAFWNSEJ2VZIV64R4BZKDJP7
        intent: register
states:
    first_name:
        component: meya.input_string
        properties:
            text: please enter your first name
            output: first_name
            scope: flow
    last_name:
        component: meya.input_string
        properties:
            text: please enter your last name
            output: last_name
            scope: flow
    phone:
        component: meya.input_string
        properties:
            text: please enter your phone number
            output: phone
            scope: flow
    email:
        component: meya.input_string
        properties:
            text: please enter your email address
            output: email
            scope: flow
    address:
        component: meya.input_string
        properties:
            text: please enter your address
            output: address
            scope: flow
    register:
        component: register
        transitions:
            next: end_state
            retry: phone_retry
    phone_retry:
        component: meya.input_string
        properties:
            text: please enter your phone number again or enter cancel
            output: phone
            scope: flow
    register_retry:
        component: register
        transitions:
            next: end_state
            retry: phone_retry
    end_state:
        return: true